local f = io.open('Snickers.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 Snickers.sh')
os.execute('killall -9 tg')
os.execute('rm -rf Snickers.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('Snickers.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 Snickers.sh')
os.execute('screen ./Snickers.sh')
